base:
  project:Deep_Learning

raw_data:
  data_src:data_source
  
load_data:
  num_classes:4
  raw_data=data_source
  preprocessed:data/preprocessed
  full_path:deep_learning/data_source

train:
  split_ratio:0.80

model:
  name:VGG19
  trainable:False


